### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by MrsBookik** [thirdweb-dev/contracts#139]
Hi

i'm curious how to run the tests?
When I run `npm run tests` or `yarn tests` it seems to do something silently but at the end it states "0 passing":

```
❯ npm run test

> @thirdweb-dev/contracts@2.1.4 test
> hardhat test

No need to generate any newer typings.
✅ Generated documentation for 120 contracts


  0 passing (0ms)
```

**Comment by kumaryash90** [comment]
`forge test` is the way to run tests in this repo. You can follow this approach as follows:
https://github.com/thirdweb-dev/contracts#running-tests
