### ISSUE TITLE
Can buy your own NFT

### ISSUE THREAD

**Issue by robo360** [thirdweb-dev/contracts#224]
The marketplace contract is set up in a way that allows someone to buy their own NFT. Would it be better if from the get go no person was able to buy a listed NFT that they own?

**Comment by nkrishang** [comment]
Hi @robo360 👋🏽 

Yes, currently the marketplace contract is set up in a way that allows someone to buy their own NFT. 

A person listing an NFT and buying it themselves is an act that sums to zero i.e. it brings the relevant state of the involved smart contracts (the marketplace, the NFT and the currency contract) back to what it was before the chain of actions was initiated. Additionally, the state changes involved in the process pertain only to that person i.e. the NFT owner themselves, and no one else.

Finally, enforcing/checking that the buyer of an NFT is not the wallet that listed it for sale in the first place, costs gas. This gas cost will be faced by all of the marketplace's buyers; even earnest ones not buying from their own listing.

And so, there is no explicit check placed in the smart contract to prevent a person from listing an NFT and buying it themselves.

I'm closing this issue; feel free to re-open the issue if you think this can lead to undesirable consequences at the smart contract level.
