### ISSUE TITLE
User/Owner Separation for NFTs - EIP4907 Integration

### ISSUE THREAD

**Issue by dotyigit** [thirdweb-dev/contracts#228]
The EIP-4907 standard makes it possible for tokens created with the ERC721 standard to be used in rental transactions. In this way, the owner and user of tokens can be separate wallets. For example, an NFT collection distributes ERC20 tokens to its users through passive staking, a user who does not yet have an NFT leases one and becomes the user of NFT. Thus, the user can earn ERC20 tokens.

This Ethereum improvement proposal helps with separating user and ownership. Although it is not a very common usage yet, it may be useful to have this option available for use among ready-to-use contracts. 

The explanation of the relevant EIP is given in the link below:
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4907.md

**Comment by nachoiacovino** [comment]
Have you seen the official release made on our site? 

https://thirdweb.com/doubledev.eth/ERC4907

**Comment by dotyigit** [comment]
Oh, I didn't see it. I just looked at the details. Thanks for your reply 🙏
