### ISSUE TITLE
Unable to pull data from Auction Listing property endTimeInEpochSeconds

### ISSUE THREAD

**Issue by gtandes** [thirdweb-dev/contracts#312]
Good day. I'm trying to implement an auction listing to a frontend website but unable to pull data from Auction Listing property endTimeInEpochSeconds or startTimeInEpochSeconds. Anybody else get the same problem or has the solution for this?

**Comment by kumaryash90** [comment]
@gtandes apologies for delayed response. Were you able to solve your issue?
Can you share more information or reach out in our discord if the issue still persists.
