### ISSUE TITLE
Failed to deploy contract

### ISSUE THREAD

**Issue by devknight216** [thirdweb-dev/contracts#327]
Failed to deploy contract
Request to upload timed out! No upload progress received in 30s
If you believe this is incorrect or the error persists, please reach out in [discord](https://discord.gg/thirdweb).

**Comment by kumaryash90** [comment]
@devknight216 apologies for delayed response. Were you able to deploy your contract?

Closing this for now. Feel free to reopen, or share this information in our discord.
