### ISSUE TITLE
Verification of contracts.

### ISSUE THREAD

**Issue by TBugelman** [thirdweb-dev/contracts#344]
Hello.

I tried your developer package and deployed marketplace contracts on testnet, can you tell me how can I verify the deployed contracts?

**Comment by kumaryash90** [comment]
@TBugelman apologies for delayed response. Which network you were trying to verify the contract on?

**Comment by abubakarafzal444** [comment]
@TBugelman Have you resolved it? I am facing the same issue.

**Comment by TBugelman** [comment]
@abubakarafzal444 no

**Comment by kumaryash90** [comment]
@TBugelman @abubakarafzal444 
For contract verification on any EVM, we have added a couple of util functions where you can verify by specifying your API key for the explorer you want to verify on. Ref PR: https://github.com/thirdweb-dev/js/pull/905

You can install this version of Typescript SDK (@thirdweb-dev/sdk: 3.10.12-nightly-5a67d5d8-20230430215002)
This will be available in the next release of SDK.

You can read more about the verification functions here: https://portal.thirdweb.com/typescript/sdk.contractverifier

Closing this issue. Feel free to reopen if the issue persists.

**Comment by TBugelman** [comment]
@abubakarafzal444 
thanks i will try this.
