### ISSUE TITLE
Sending native token (ETH) using AirdropERC20 is returning error: `Incorrect native token amount`

### ISSUE THREAD

**Issue by kienngo98** [thirdweb-dev/contracts#360]
Hi, I'm playing with the AirdropERC20 contract. It works well with ERC20 tokens however I'm just stuck at the last step for sending native tokens (eth/matic/bnb/avax).

Here's my code in React using <Web3Button>: It's trying to end 1 native token to another address
```
<Web3Button
      contractAddress="0xa56266B854287e15612b2A7d6077f4CECdF508D8"
      action={(contract) => {
        contract.call(
          "airdrop",
          NATIVE_TOKEN_ADDRESS,
          props.callerAddress,
          ["0xd587924ce50c703182409d7d45eb79a9fbe6b49d"],
          ["1000000000000000000"]
        );
      }}
      overrides={{
        value: parseEther("1"),
        gasLimit: 1000000
      }}
    >
      Batch send
</Web3Button>
```
Here's the link to Thirdweb Explorer: https://thirdweb.com/avalanche-fuji/0xa56266B854287e15612b2A7d6077f4CECdF508D8

Here's the error in the console: `Incorrect native token amount`
![image](https://user-images.githubusercontent.com/26052673/228128635-948766ac-dd82-4dff-bad4-9206199cac0f.png)

However the following input works in Thirdweb Explorer:
![image](https://user-images.githubusercontent.com/26052673/228128952-63ad5128-6c26-4701-8679-4a907847bbef.png)

What am I missing?

**Comment by kumaryash90** [comment]
hey @kienngo98 ,
I just checked, the transaction seems to have worked. 1 Avax was transferred to the recipient address:
https://testnet.snowtrace.io/tx/0xd4543f4ae4004fe33d72926a17c03b961e67c2f173f544fc1e45bd42d9c9dc25#internal

It is weird that you get this error though.
Can you post this error in our discord. We can continue there.

**Comment by kienngo98** [comment]
Hi @kumaryash90 , I have created a thread here: https://discord.com/channels/834227967404146718/1090246555518373888
Thanks!

**Comment by kienngo98** [comment]
Hey guys for @kumaryash90  has helped me fix it. Basically the `value` has to be passed inside `contract.call()` instead of the `overrides` props.
Here's the code:
```
<Web3Button
      contractAddress="0xa56266B854287e15612b2A7d6077f4CECdF508D8"
      action={(contract) => {
        contract.call(
          "airdrop",
          NATIVE_TOKEN_ADDRESS,
          address,
          ["0xd587924ce50c7031************************"],
          ["1000000000000000000"],
          {
            value: parseEther("1"),
          }
        );
      }}
      // overrides={{
      //   value: parseEther("1"),
      //   gasLimit: 1000000,
      // }}
    >
      Batch send
    </Web3Button>
```
