### ISSUE TITLE
optimizations

### ISSUE THREAD

**Issue by malik672** [thirdweb-dev/contracts#376]
instead of require, why not just use custom errors, beside more gas would have been saved using yul

**Comment by malik672** [comment]
always use pre-increment method when incrementing one of your code went 443 less in gas for one of this reason and its a loop and you don't have to initialize to zero by default variables are already zero when created that cost an additional 8 in gas

**Comment by malik672** [comment]
this part here is weird, i think the hardcoding the function selector is better, then using bit manbipulation to add the params to the end of the selector saves more gas and tbh i think this is better using yul
`  (bool success_, bytes memory data_) = _currency.call(
                abi.encodeWithSelector(IERC20.transferFrom.selector, _from, _to, _amount)
            );
`

**Comment by malik672** [comment]
if (_amount == 0) {
            success = true;
            return success;
        }
this tbh is so bad you don't need to do success = true, return success you can just return 1, thats still true

**Comment by malik672** [comment]
`return string(abi.encodePacked(batchUri, "0"));`
you could have done this yourself, if you do not need the same string in the function again you should just encode this using the length and bit manipulation instead of abi.encodePacked which actually creates a clone in memory then encodes it

**Comment by malik672** [comment]
the best way to solve this issue, just write in yul, i can't go through the whole codebase

**Comment by nkrishang** [comment]
Hey @malik672 👋🏽  appreciate the suggestions. We're starting Solidity optimization work; want to make a PR containing your suggestions? That'd be super helpful.

Regarding [custom errors](https://github.com/thirdweb-dev/contracts/issues/376#issue-1685911145) -- we've attempted to introduce them to the codebase before. We'll introduce them to the codebase once we build decent error message rendering for them in our SDK layer.

**Comment by malik672** [comment]
thank you, will love to
