### ISSUE TITLE
ERC721AVirtualApproveUpgradeable => Identifier not found or not unique => AddressData

### ISSUE THREAD

**Issue by codev911** [thirdweb-dev/contracts#389]
Hei there, i have try library and got some issue about this, please fix it.

**Comment by codev911** [comment]
<img width="452" alt="gambar" src="https://github.com/thirdweb-dev/contracts/assets/53482087/36745eea-0b12-4c57-874d-9207dedcd45e">

**Comment by nkrishang** [comment]
Hi @codev911 looks like I'm getting to this very late, apologies! We have fixed this issue; updating to the latest version of `@thirdweb-dev/contracts` should resolve the error.
