### ISSUE TITLE
Managed Smart Wallet contracts fail to Truffle compile: "lib/dynamic-contracts" not found

### ISSUE THREAD

**Issue by jblewnormal** [thirdweb-dev/contracts#399]
I'm following the Thirdweb docs [here](https://portal.thirdweb.com/solidity/base-contracts/managed-account-factory) for the new Managed Smart Wallets and have created a new AccountFactory and Account contract as there are some customizations we require.

```
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.11;

import "../node_modules/@thirdweb-dev/contracts/smart-wallet/managed/ManagedAccountFactory.sol";

contract NormalAccountFactory is ManagedAccountFactory {
    constructor(IEntryPoint _entrypoint) ManagedAccountFactory(_entrypoint) {}
}
```

After installing the latest `@thirdweb-dev/contracts@3.5.4` to my Truffle project and setting up these custom contracts, I continue to get the following compile errors when running migrations or tests:

```
ParserError: Source "lib/dynamic-contracts/src/core/Router.sol" not found
  --> project:/node_modules/@thirdweb-dev/contracts/smart-wallet/managed/ManagedAccount.sol:18:1:
   |
18 | import "lib/dynamic-contracts/src/core/Router.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

,ParserError: Source "lib/dynamic-contracts/src/interface/IBaseRouter.sol" not found
 --> project:/node_modules/@thirdweb-dev/contracts/smart-wallet/utils/BaseRouter.sol:7:1:
  |
7 | import "lib/dynamic-contracts/src/interface/IBaseRouter.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

,ParserError: Source "lib/dynamic-contracts/src/core/Router.sol" not found
  --> project:/node_modules/@thirdweb-dev/contracts/smart-wallet/utils/BaseRouter.sol:10:1:
   |
10 | import "lib/dynamic-contracts/src/core/Router.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

,ParserError: Source "lib/dynamic-contracts/src/presets/utils/StringSet.sol" not found
  --> project:/node_modules/@thirdweb-dev/contracts/smart-wallet/utils/BaseRouter.sol:13:1:
   |
13 | import "lib/dynamic-contracts/src/presets/utils/StringSet.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

,ParserError: Source "lib/dynamic-contracts/src/presets/utils/ExtensionState.sol" not found
  --> project:/node_modules/@thirdweb-dev/contracts/smart-wallet/utils/BaseRouter.sol:14:1:
```

Thirdweb's Managed Smart Account contracts require an additional Thirdweb repo (@thirdweb-dev/dynamic-contracts), which can be seen in the git modules [here](https://github.com/thirdweb-dev/contracts/blob/main/.gitmodules#L7).

I also understand that `@thirdweb-dev/contracts@3.5.4` has a `/lib` directory housing the various git modules used throughout the project, but it seems that these aren't included within the npm package. Inspecting `@thirdweb-dev/contracts` within my node_modules reveals zero configuration for these required git modules and the `/lib` directory is full of random contracts (i.e. `TWAddress.sol`, `TWStrings.sol`, etc), which is why these errors are happening.

Does anyone know how to best approach fixing this, or is this potentially a bug within the npm package?

Thanks!

**Comment by jblewnormal** [comment]
Misclick

**Comment by nkrishang** [comment]
Hey @jblewnormal 👋🏽  I'm going to try to debug this on my end; would like to get rid of these dependency issues and unblock you from deploying. For the time being, is `ManagedAccountFactory` the only contract you're trying to use?

**Comment by jblewnormal** [comment]
Thank you so much @nkrishang ! We have contract overwrites for both `ManagedAccountFactory` and `ManagedAccount` following your [documentation here](https://portal.thirdweb.com/solidity/base-contracts/managed-account-factory).

I've forked this repo and am working on finding a solution as well. Will update here with any findings.

**Comment by nkrishang** [comment]
Hey @jblewnormal 👋🏽 would love to know what the outcome was on your on end (in regards to this issue).

We're planning to move over to forge/foundry entirely (and thus, phasing out hardhat). In the process, we're trying to ensure that consuming the repo's code via both node modules, or git modules is equally seamless.

Would love to know what resolution you came to with this issue so we can learn.
