### ISSUE TITLE
deploy  bug

### ISSUE THREAD

**Issue by Osub** [thirdweb-dev/contracts#448]
npx hardhat run ./scripts/deploy/fullV2Setup.ts
```
   .then(f => f.deploy(thirdwebFee.address, options))
                                                 ~~~~~~~
scripts/deploy/fullV2Setup.ts:112:46 - error TS2554: Expected 0-1 arguments, but got 2.

112     .then(f => f.deploy(thirdwebFee.address, options))
                                                 ~~~~~~~
scripts/deploy/fullV2Setup.ts:121:46 - error TS2554: Expected 0-1 arguments, but got 2.

121     .then(f => f.deploy(thirdwebFee.address, options))
                                                 ~~~~~~~
scripts/deploy/fullV2Setup.ts:129:46 - error TS2554: Expected 0-1 arguments, but got 2.

129     .then(f => f.deploy(thirdwebFee.address, options))
                                                 ~~~~~~~
scripts/deploy/fullV2Setup.ts:137:99 - error TS2554: Expected 1-2 arguments, but got 3.
```
![image](https://github.com/thirdweb-dev/contracts/assets/7599190/609923e8-ab29-405b-bc49-b43e367ab0f1)

**Comment by nkrishang** [comment]
Hey @Osub 👋🏽  Looks like the script is outdated by > 1 year, since it contains `thirdweb Fee` which we phased out long ago.

Would love to learn what you're trying to do with this script so I can point you to the right resource / tool.

Additionally, (as mention in https://github.com/thirdweb-dev/contracts/issues/399 recently) we're in the process of moving away from hardhat to forge/foundry entirely.

**Comment by Osub** [comment]
If I want to deploy the contract, the forge/foundry tutorial for this project

**Comment by nkrishang** [comment]
Hey @Osub today at thirdweb, we use _keyless deploy_ for bootstrapping any EVM blockchain with the implementation contracts of our prebuilts ([related blogpost](https://blog.thirdweb.com/permissionless-infrastructure-deployments-on-900-evm-chains/) with explanation).

You can look at [this script in the repo](https://github.com/thirdweb-dev/contracts/blob/main/scripts/deploy-prebuilt-deterministic/deploy-deterministic-std-chains.ts) that deploys the implementation of any given prebuilt contract in the repo e.g. `DropERC721` on a select list of chains, at the same deterministic address.

If you're looking to deploy contracts, I suggest looking at our [Deploy documentation](https://portal.thirdweb.com/deploy) for the best way to deploy contracts.

Apologies for getting back late! I'm closing this issue for now. Feel free to comment an update, or reach out in the [thirdweb discord](https://discord.gg/beY2nwTP).
