### ISSUE TITLE
[Question] Extending marketplace permission

### ISSUE THREAD

**Issue by tarikhagustia** [thirdweb-dev/contracts#460]
Hi there,

I was thinking about extending marketplace permissions, I need a "buyer" permission. so not every address can buy a listing. it is possible to do that?

**Comment by kumaryash90** [comment]
Hey @tarikhagustia,
There's a `approveBuyerForListing` function which can be used here. You can set a listing as `reserved` when creating it, and then approve buyers for the listing.
