### ISSUE TITLE
getAllProposals for vote contract fails to return data

### ISSUE THREAD

**Issue by mykcryptodev** [thirdweb-dev/contracts#462]
After 6 or 7 proposals that have descriptions of ~250 words, the [getAllProposals](https://github.com/thirdweb-dev/contracts/blob/main/contracts/vote/VoteERC20.sol#L122) function of the vote contract no longer responds with data.

Here are two examples onchain:

https://goerli.basescan.org/address/0x570f497964efb9564af6fc4175809c8e8ec2263e#readContract
https://goerli.basescan.org/address/0x314bf06caee105883b5f8f5df4f6aedee9abc436#readContract

It breaks the dashboard for the proposal extension page.

![Screenshot 2023-08-11 at 4 27 14 PM](https://github.com/thirdweb-dev/contracts/assets/89474773/22970067-f470-4016-a87a-27a14b882b8c)

**Comment by mykcryptodev** [comment]
I am thinking it might be related to the Base chain because Goerli (Eth) is responding past my 7th proposal
https://thirdweb.com/goerli/0xbE1127E57770f1F9E5734a973C1FFAb5E5BB1469/proposals

**Comment by kumaryash90** [comment]
Hey @mykcryptodev , did it get resolved? 
I believe it has something to do with gas limit for `eth_call`, may differ across chains / providers. Unfortunately right now we don't have a way to query this in batches / specific range. Will see if we can update this function in a future release.

**Comment by alfheimrShiven** [comment]
> Hey @mykcryptodev , did it get resolved? I believe it has something to do with gas limit for `eth_call`, may differ across chains / providers. Unfortunately right now we don't have a way to query this in batches / specific range. Will see if we can update this function in a future release.

Hey @kumaryash90 do you mean to say that various block explorers can have different gas limits for `eth_call` and that could be the reason why we get a response to `getAllProposal()` on [ThirdWeb's UI](https://thirdweb.com/goerli/0xbE1127E57770f1F9E5734a973C1FFAb5E5BB1469/proposals) but not on [BaseScan](https://goerli.basescan.org/address/0x570f497964efb9564af6fc4175809c8e8ec2263e#readContract)? Cuz the testnet is common (Goerli).

In fact I checked for the balance of `0xbE1127E57770f1F9E5734a973C1FFAb5E5BB1469` contract on 3 block explorers and _the BaseScan explorer doesn't even show the updated balance._

Balance on [Goerli Etherscan](https://goerli.etherscan.io/address/0xbE1127E57770f1F9E5734a973C1FFAb5E5BB1469): 0.0134 ETH
Balance on [BlockScout](https://eth-goerli.blockscout.com/address/0xbE1127E57770f1F9E5734a973C1FFAb5E5BB1469): 0.0134 ETH
Balance on [BaseScan](https://goerli.basescan.org/address/0xbE1127E57770f1F9E5734a973C1FFAb5E5BB1469): 0 ETH

BaseScan's data seems to be outdated or buggy.
