### ISSUE TITLE
Missing benchmarks for multiple contracts

### ISSUE THREAD

**Issue by allan-wei-tx** [thirdweb-dev/contracts#471]
I personally want to help improve gas efficiency with `smart-wallet` contracts through gas optimization bounty program, but I can't find related benchmark tests in the folder.

**Comment by WEI-NERD** [comment]
wen bench marks for those contracts, may I ask?

**Comment by nkrishang** [comment]
Hey @allan-wei-tx apologies, getting to this a bit late.

We have gas benchmarks set-up for our `Account` + `AccountFactory` contracts: https://github.com/thirdweb-dev/contracts/blob/main/src/test/benchmark/AccountBenchmark.t.sol

You can run each benchmark tests and inspect the gas consumption of calls via (example):
```bash
forge test --mc AccountBenchmarkTest --mt test_state_createAccount_viaEntrypoint
```

We'll work on making benchmarks more visible. In the meantime, you can run the tests in the `src/test/smart-wallet/` with the `forge test -vvvv` forge command to get the full gas consumption breakdown of all involved contract calls.
