### ISSUE TITLE
Add test & gas benchmark for Marketplace contract to gasreport.txt

### ISSUE THREAD

**Issue by kien-ngo** [thirdweb-dev/contracts#472]

**Comment by SonuBardai** [comment]
Hey @kien-ngo! I would love to help with this issue. I've setup the project locally and I'm going through the marketplace contract and all the related code. I see that there's already some tests written for the marketplace contract. Can you help me with what would be a good place to start, and what functions we're looking to add tests for? I'm also on the discord channel if that's a better place to talk about this. Thanks

**Comment by kien-ngo** [comment]
Hey @SonuBardai, thanks for reaching out. Let me tag @nkrishang here since I'm not the one in charge so I'm not sure what the team have in mind in terms of current road map. 

Feel free to reach out on Discord anyway ^

**Comment by nkrishang** [comment]
Hey 👋🏽 I'll figure out an easier way to view all our contract benchmarks. 

In the meantime, you can run any of the MarketplaceV3 tests using the `forge test` command with `-vvvv` tag to get the full gas consumption profile of any contract calls involved. Example:

```bash
forge test --mc MarketplaceEnglishAuctionsTest --mt test_state_createAuction -vvvv`
```
