### ISSUE TITLE
Custom Tokens Not Deducted on NFT Claim

### ISSUE THREAD

**Issue by jagzmz** [thirdweb-dev/contracts#488]
I have deployed the [OpenEditionERC721](https://thirdweb.com/thirdweb.eth/OpenEditionERC721/1.0.0) contract on the Polygon Mumbai network. Here's the [contract address](0x59280EeE2C64f9Fb559c0E44f90e7d71bDF97196).

The contract accepts payments in a custom contract of [DERC 20](0xfe4F5145f6e09952a5ba9e956ED0C25e3Fa4c7F1).

![image](https://github.com/thirdweb-dev/contracts/assets/34797952/233ac093-64e0-4ab8-8049-2c915b49f331)

I only have 2 DERC20 tokens in my wallet address `0x30372164971e8174315e3D0724bFc44fe53EA195`.

When I try to purchase an NFT, the transaction completes successfully, but the tokens are not deducted from my wallet. Shouldn't the contract throw an error before the transaction?

**Comment by nachoiacovino** [comment]
hey @jagzmz, if you're the primary sale recipient for your contract (which you are), you're basically sending the tokens to yourself, so they're being deducted then added automatically.

If you try claiming from a different wallet you'll see the tokens moving, I hope this clarifies it.

**Comment by jagzmz** [comment]
Hi @nachoiacovino , I understand that. I tried claiming to another wallet , but it's the same, transaction is getting successful. As you can see I have set the quantity to 1000 tokens, even if I am claiming to myself, shouldn't contract fail since I do not have that amount of tokens in first place?
