### ISSUE TITLE
Staking721Upgradeable - _calculateRewards out of gas problem 

### ISSUE THREAD

**Issue by sayedex** [thirdweb-dev/contracts#502]
```
    function _calculateRewards(address _staker) internal view virtual returns (uint256 _rewards) {
        Staker memory staker = stakers[_staker];

        uint256 _stakerConditionId = staker.conditionIdOflastUpdate;
        uint256 _nextConditionId = nextConditionId;

        for (uint256 i = _stakerConditionId; i < _nextConditionId; i += 1) {
            StakingCondition memory condition = stakingConditions[i];

            uint256 startTime = i != _stakerConditionId ? condition.startTimestamp : staker.timeOfLastUpdate;
            uint256 endTime = condition.endTimestamp != 0 ? condition.endTimestamp : block.timestamp;

            (bool noOverflowProduct, uint256 rewardsProduct) = SafeMath.tryMul(
                (endTime - startTime) * staker.amountStaked,
                condition.rewardsPerUnitTime
            );
            (bool noOverflowSum, uint256 rewardsSum) = SafeMath.tryAdd(_rewards, rewardsProduct / condition.timeUnit);

            _rewards = noOverflowProduct && noOverflowSum ? rewardsSum : _rewards;
        }
    }
```
 if any admin change the reward 50 times the contract will get stucks .. can y check?

**Comment by kumaryash90** [comment]
I think this issue has been answered over email. Closing this.
In case you're not the person who reported it over email, let us know. 

This is the summary of the issue reported and the design decisions:

The design of the reward mechanism here assumes that the admin would not need to / want to set the conditions a large number of times. The initial settings are applied during deployment, and the setter functions are provided as a convenience in case the admin needs to fix an incorrectly set value or revise it at some point. 

The trust assumptions inherent in the design allow an admin to have control over various things such as staking conditions, reward tokens etc. While the out-of-gas / function getting stuck scenario is a possibility if the number of conditions reach very high values, it is not expected to occur as part of **normal operation** of the contract. 

It was noticed that this design and trust assumptions are not called out explicitly in the docs. We'll update these details in the docs and thirdweb portal. Moreover, we'll look into the design of the contract to make it more efficient for future releases.
