### ISSUE TITLE
Deposit Reward Tokens (depositRewardTokens) area has a problem.

### ISSUE THREAD

**Issue by berkeguleryuz** [thirdweb-dev/contracts#514]
The contract has a problem. I can not deposit my ERC20 token in the contract. It always has a problem.
When I try with just amount area:
ERC20: insufficient allowance (but I have and I took this information in my client-side too)

When I try with Native Token Value area:
missing revert data in call exception; Transaction reverted without a reason string

if I write both of them:
missing revert data in call exception; Transaction reverted without a reason string

**Comment by berkeguleryuz** [comment]
Also it is in BNB Testnet chain 
([StakeERC721](https://thirdweb.com/thirdweb.eth/NFTStake/1.0.3)
Contract for staking ERC721 NFTs, for ERC20 tokens as rewards.


[thirdweb.eth](https://thirdweb.com/thirdweb.eth))

**Comment by kumaryash90** [comment]
hey @berkeguleryuz 
can you share your staking contract address / dashboard-link?

**Comment by nkrishang** [comment]
Hi @berkeguleryuz 👋🏽 were you able to resolve your issue?

I'm closing this issue for now, but please feel free to comment an update containing your staking contract address / dashboard-link. Thank!

Also, feel free to tag `@thirdweb Support` with your issue in the [thirdweb discord](https://discord.gg/beY2nwTP).
