### ISSUE TITLE
npx thirdweb create contract

### ISSUE THREAD

**Issue by Miguelcividanes1977** [thirdweb-dev/contracts#515]

**Comment by alfheimrShiven** [comment]
Hey @Miguelcividanes1977 could you provide more information about the issue you're facing? Thanks.

**Comment by nkrishang** [comment]
Hi @Miguelcividanes1977 👋🏽 closing this issue for now. Feel free to comment here again with more info about your issue. Or, you can tag `@thirdweb Support` with this issue in the [thirdweb discord](https://discord.gg/beY2nwTP).
