### ISSUE TITLE
TCP error when running `forge build` on the `contracts` repo

### ISSUE THREAD

**Issue by alfheimrShiven** [thirdweb-dev/contracts#517]
Hi, I'm getting the following error after cloning the repo, installing all deps and running `forge build`:

```zsh
Error: 
error sending request for url (https://raw.githubusercontent.com/alloy-rs/solc-builds/55ef6c89b8a09c16feee4a424f8a53f822831a61/macosx/aarch64/list.json): error trying to connect: tcp connect error: Operation timed out (os error 60)
```
The `raw.githubusercontect.com` is not returning any response to the `solc-builds` list request. Is anyone facing the same? Need help to get through this. Thanks.

**Comment by kumaryash90** [comment]
hey @alfheimrShiven 
did you figure it out? or are you still facing this issue?

**Comment by alfheimrShiven** [comment]
Hey @kumaryash90 I solved this by enabling `auto_detect_solc = true` in my `foundry.toml`.

```
# solc-version = "0.8.12"
auto_detect_solc = true
...
```

Do you have any other solution for this?

**Comment by alfheimrShiven** [comment]
My network provider's DNS was blocking `https://raw.githubusercontent.com`. This seems to be a common issue for Indians using JIO or Airtel network.

The solution is to switch your DNS to Google's Public DNS `8.8.4.4` instead of using Airtel's or Jio's DNS.
