### ISSUE TITLE
ZKsync deploy

### ISSUE THREAD

**Issue by VXEAD** [thirdweb-dev/contracts#529]
Hello, I have a problem/question, when I deployed a token, I was debited, but it was a gasless transaction, but 40 cents in ethereum were debited. + in the metamask explorer, the transaction is not displayed like I am in the starknet "Deploy" just nothing, also in the debit card, an empty contract. Is this normal?
Also, is it necessary to verify the smart contract in the zksync explorer?

**Comment by kumaryash90** [comment]
hey @VXEAD 
Which contract did you deploy? And from thirdweb dashboard or a script?

The deployment transaction itself is not gasless on zksync, even though you may have gasless settings in your sdk instance.

**Comment by kumaryash90** [comment]
Deployments for zksync network go through zksync's system contracts. This is different from deployments on other networks where we use a factory for deployments.
Unfortunately, gasless deployments won't work on zksync.

Hope this answers your query.
