### ISSUE TITLE
Multiple currency support in MarketplaceV3 DirectListings contract.

### ISSUE THREAD

**Issue by goldnite** [thirdweb-dev/contracts#590]
MarketplaceV3 contracts only support a single currency for DirectListing.
It would be nice to support multiple currencies when making payments.
For example, an NFT could be sold for 1 ETH or 2000 USDT.
It can facilitate NFT transactions among marketplace users.

**Comment by nkrishang** [comment]
Hi @goldnite 👋🏽  the `MarketplaceV3` contract does have this feature. See `DirectListings.approveCurrencyForBuyer` here: https://github.com/thirdweb-dev/contracts/blob/main/contracts/prebuilts/marketplace/direct-listings/DirectListingsLogic.sol#L215
