### ISSUE TITLE
[OffersLogic] Error in expiration time validation

### ISSUE THREAD

**Issue by martynasmuizys** [thirdweb-dev/contracts#657]
Function `_validateNewOffer(OfferParams memory _params, TokenType _tokenType)` has an error in expiration time validation:
```
require(
    _params.expirationTimestamp + 60 minutes > block.timestamp,
    "Marketplace: invalid expiration timestamp."
);
```
This `require` statement allows to create offers in the past. If I understand correctly, goal was to make offer duration at least one hour. In that case shouldn't it be:
```
require(
    _params.expirationTimestamp >= block.timestamp + 60 minutes,
    "Marketplace: invalid expiration timestamp."
);
```
Function `_validateExistingOffer(Offer memory _targetOffer)` should be updated accordingly (changed `>` to `>=`).

**Comment by kumaryash90** [comment]
Hey @martynasmuizys,

Thanks for reaching out. 
The intention behind setting timestamp checks this way in `DirectListings` and `Offers` was to keep the timestamps within one hour of block timestamp when creating listings etc.

You can read more about this in the audit report here, which points out no risk to the contract but potential data inaccuracy. And the changes made.
https://0xmacro.com/library/audits/thirdweb-6#L-1

**Comment by martynasmuizys** [comment]
Thank you for clarifying. Now that I think about it, I'm starting to understand this design choice.
